import { chromium } from 'playwright';
const OUT=process.argv[2], planId=process.argv[3];
const b=await chromium.launch();
const p=await (await b.newContext({viewport:{width:820,height:1160},deviceScaleFactor:2})).newPage();
await p.goto(`http://127.0.0.1:4200/print/${planId}`,{waitUntil:'networkidle'});
await p.evaluate(()=>document.fonts.ready);
await p.waitForSelector('.doc',{timeout:45000});
await p.emulateMedia({media:'print'});
await p.waitForTimeout(400);
await p.screenshot({path:`${OUT}/print-media.png`});
console.log('print-media captured');
await b.close();
